# Generated by Django 5.1.1 on 2024-09-17 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_person',
        ),
        migrations.RemoveField(
            model_name='product',
            name='npm',
        ),
    ]
